spring:
  application:
    name: Luiggi ama Java
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/db
    username: sa
    password: password
    driverClassName: org.h2.Driver
    dialect: 
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'